using System;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.InputSystem.Utilities;
using static SemiCircleFoldingAlgorithm;

/**
 * script to be attatched to each glider to calculate aerodynamic pathing based on PaperAirplanePhysicsAttributes and current velocity/rotations
 * 
 * @author Grant Benson
 **/
public class GliderFlight : MonoBehaviour
{
    [Header("Constants")]
    private const float ACCELERATION_OF_GRAVITY = 9.81f; //  m/s^2
    private const float DENSITY_OF_AIR = 1.225f; //  kg/m^3 at sea level 15 degrees C
    private const float DYNAMIC_VISCOSITY_OF_AIR = .0000181f; //kg/ms at sea level 15 degrees C
    private const float BLASIUS_LAMINAR_DRAG_COEFFICIENT = 1.328f;

    [Header("Script and object refs")]
    private GeneSequence geneSeq; //gene sequence containing representations for glider creation
    private PaperAirplanePhysicsAttributes physNums;
    private Rigidbody rb; //rigid body for glider to perform torque on
    //TODO: add a mesh collider and use the mesh generated by triangleMeshGenerator
    private GeneManager geneManager;//ref to gene manager to save upon crash

    //fields and callback to communicate fitness with gene manager via game manager callback
    private float startingFitness;
    private float fitnessScore;
    private float startingElevation;
    private float fallHeight = 5; //allow gliders to fall 5 meters before being destroyed
    private float previousTotalDrag = 0; //TODO: consider setting approximation on start
    private float previousTotalLift = 0; //TODO: consider setting approximation on start
    private float previousCOPXOffset = 0; //setting approximation on start
    private Action<GliderFlight, string, float> onCrashCallback;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        //float maxLifeSpan = 8f; // Set lifespan before destruction
        //Destroy(gameObject, UnityEngine.Random.Range(2, maxLifeSpan)); // Destroys this GameObject after max lifeSpan seconds
        // Get the current GameObject and set fitness score to x value on start and set starting elevation to y value
        startingFitness = transform.position.x;
        startingElevation = transform.position.y;
        rb = GetComponent<Rigidbody>(); //TODO: get rigid body of glider
        rb.centerOfMass = physNums.getCenterOfMass(); //set rigid body center of mass from phys calcs
        //set mass of rb as well from phys calcs
        rb.mass = physNums.getMass();
        //angle the glider appropriately based on intial AOA from gene sequence
        transform.rotation = Quaternion.Euler(0, 0, geneSeq.GetInitialAngle());
        //set the previous center of pressure to be MAC / 3 (approximation for delta wings)
        previousCOPXOffset = physNums.getMAC / 3;
    }

    // Update is called once per frame
    void Update()
    {
        //TESTING: using gene sequence.GetInitialVelocity() to create linear flight paths
        if (physNums.CanFly())
        {
            //Debug.Log("glider fly :)");
            //add movement to parent position
            float xMovementAmount = geneSeq.GetInitialVelocity() * Time.deltaTime;
            float yMovementAmount = 2 * Time.deltaTime;
            transform.position += new Vector3(xMovementAmount, -yMovementAmount, 0);
        }

        //END OF TESTING: linear flight is successfully being tracked by camera manager

        //AERODYNAMICS: start of real physics section to apply lift, gravity, and drag

        if (checkForEndOfFlight()){
            //destroy the glider if it has fallen down the specified height
            float finalFitnessScore = getFitnessScore();
            //update gene manager with the gene sequence and fitness score (distance travelled in x direction)
            geneManager.UpdateBestCompetitor(geneSeq, finalFitnessScore);
            onCrashCallback(this, geneSeq.getName(), finalFitnessScore); // Pass the glider flight instance to the callback to be destroyed
        }

        //first calculate direction
        Vector3 relativeAirflow = -rb.linearVelocity.normalized; //determine relative air flow in order to apply drag on the COP in opposite direction
                                                                 //float AOA = getAngleOfAttack(relativeAirflow); //determine angle of attack (AOA) 0 while flat, positive for up, negative for down
        Vector3 liftDirection = Vector3.Cross(relativeAirflow, transform.right).normalized; //lift will be applied tn the COP perpendicular to relative air flow and right vector of glider
        Vector3 dragDirection = relativeAirflow; //drag always acts opposite of motion
                                                 //get velocity mag to get dynamic pressure (q) =  p v^2 1/2  that will be used in drag equations
        float velocityMag = rb.linearVelocity.magnitude;
        float dynamicPressure = Mathf.Pow(velocityMag, 2) * DENSITY_OF_AIR / 2;

        //second calculate forces (lift will be 0 and drag will be higher if AOA is at or above stall angle)
        //COM calcs
        //gravity will always pull directly down on the COM, the only force balancing out the forces on the COP
        Vector3 forceOnCenterOfMass = new Vector3(0, -ForceOfGravity(), 0); //apply force of gravity downward on COM
                                                                            //COP calcs
        float liftForce = getLiftForce(velocityMag, dynamicPressure);
        //TODO: combine into one vector3 once accuracy in ensured to improve performance
        Vector3 drag = getDragForce(liftForce, velocityMag, dynamicPressure) * dragDirection;//DragVector = dragForce * dragDirection
        Vector3 lift = liftForce * liftDirection; //LiftVector = liftForce * liftDirection
                                                  //Vector3 forceOnCenterOfPressure = drag + lift; //add drag and lift to get all forces acting on center of pressure

        //third apply forces at COP and COM
        //TODO: assure accuracy of COP, COM, lift force, and drag force
        //rb.AddForce(forceOnCenterOfMass, ForceMode.Force); //apply gravitational force to center of mass (COM)
        //rb.AddForceAtPosition(drag + lift, getCenterOfPressureEstimate(velocityMag, dynamicPressures), ForceMode.Force); //apply drag and lift force to center of pressure (COP)

    }

    //function passed in by game manager to update ui/camera on death, avoinding any creation after scene close
    public void SetOnDestroyCallback(Action<GliderFlight, string, float> callback)
    {
        onCrashCallback = callback; //calls HandleGliderDestroyed function in game manager after all data is used
    }

    //TESTING function to determine if COM of gliders are being correctly computed and maintained
    //Ensure "Gizmos" is enabled in the Scene View (top right corner).
    void OnDrawGizmos()
    {
        //TODO: use this to correct COM and COP unctions
        Gizmos.color = Color.green;
        Gizmos.DrawSphere(getPositionOfCOM(), .25f); //draw green sphere to visualize center of mass (COM) on each glider
        float velocityMag = rb.linearVelocity.magnitude;
        float dynamicPressure = Mathf.Pow(velocityMag, 2) * DENSITY_OF_AIR / 2;
        Gizmos.color = Color.yellow;
        Gizmos.DrawSphere(getCenterOfPressureEstimate(velocityMag, dynamicPressure), .25f); //draw yellow sphere to visualize center of pressure (COP) on each glider
    }

    //calculate the center of pressure for glider's lift and drag act upon
    private Vector3 getCenterOfPressure(){
        //TODO actually calculate the position of COP via lift integral method (more accurate than estimation)
        return transform.position;
    }

    //COP can be estimated by chord length / 4 * (1 - moment coefficient / lift coefficient)
    //COP is how far from the nose the COP is
    private Vector3 getCenterOfPressureEstimate(float vMag, float q){
        float radius = physNums.getRadius();
        float coefficientOfLift = getCoefficientOfLift(vMag, q);
        float offset = radius / 4 * (1 - getCoefficientOfMomentum(coefficientOfLift) / coefficientOfLift); //chord length = radius for our wing
        previousCOPXOffset = offset; //offset is needed for coefficient of momentup
        //TODO: test COP estimates
        Vector3 COP = transform.position + new Vector3(radius - offset, 0, 0); //position as at back so add radius to get to nose then minus cop offset
        return COP;
    }

    //helper function to get coefficient of momentum for COP estimate
    //the formula needs coefficient of momentum so using the previous COP offset is the current solution
    private float getCoefficientOfMomentum(float liftCoefficient){
        //Cm = -Cl (COPx - MAC / 4) / MAC
        float MAC = physNums.getMAC();
        float momentumCoefficient = -liftCoefficient * (previousCOPXOffset - MAC / 4) / MAC;
        return momentumCoefficient;
    }

    //adds glider position with set center of mass to get current COM position (might have to reposition glider prefab)
    private Vector3 getPositionOfCOM()
    {
        //if (rb != null) return transform.position + rb.centerOfMass;//use null check if null ref occurs
        //else return transform.position;
        return transform.position + rb.centerOfMass;
    }

    //returns true if glider has fallen the fall height of the flight (or more), false if not
    private bool checkForEndOfFlight(){
        return transform.position.y <= startingElevation - fallHeight;
    }

    //AOA will be positive nose up, 0 while flat, and negative while nose down
    private float getAngleOfAttack(Vector3 relativeAirflow){
        // Angle Of Attack (AOA) will be 0 if relative airflow vector is going directly forward
        float angleOfAttack = Vector3.Angle(relativeAirflow, transform.forward); //get angle
        float sign = Mathf.Sign(Vector3.Dot(Vector3.Cross(relativeAirflow, transform.right), transform.forward)); //determine if going up or down
        return angleOfAttack * sign;  // AOA is positive for nose-up, negative for nose-down
        
    }

    //adds the skin friction,form, and induced drag forces then returns
    //not accounting for interference drag (from folds and wings meeting middle part)
    private float getDragForce(float liftForce, float vMag, float q)
    {
        //skin friction is dynamic pressure * wetted surface area * skin friction coefficient
        float skinFriction = q * physNums.GetTotalArea() * getCoefficientOfSkinFrictionDrag(vMag); //friction generated when air molecules stick to flying object (10-30% of drag)
        //induced drag is force of lift^2 / (dynamic pressure * wings surface area * PI * oswald efficiency factor * aspect ratio)
        float aspectRat = getAspectRatio(physNums.getWingspan(), getEffectiveWingArea()); //consider setting this at start or moving to physnums to calc + get
        float inducedDrag = Mathf.Pow(liftForce, 2) / (q * getEffectiveWingArea() * Mathf.PI * getOswaldApproximation(aspectRat) * aspectRat);
        //form drag is dynamic pressure * Sfront * form drag coefficient
        float formDrag = q * getEffectiveFrontArea() * getCoefficientOfFormDrag(vMag);

        //sum all drag contributors and return total drag
        return skinFriction + inducedDrag + formDrag;
    }

    //function to get effective wing area given angle of attack
    private float getEffectiveWingArea(){
        return physNums.getTopArea();
    }

    //function to get effective nose area given angle of attack
    private float getEffectiveFrontArea(){
        return physNums.getFrontArea();
    }

    //get lift force function: Flift = p v^2 / 2 SAwing CLift = q * SAwing * CLift
    private float getLiftForce(float vMag, float q)
    {
        //return 0f; //consider returning 0 if AOA is too high (stall out effect)
        float wingArea = getEffectiveWingArea();
        float liftForce = q * wingArea * getCoefficientOfLift(vMag, q); //q * SAwing * CLift
        previousTotalLift = liftForce;
        return liftForce;
    }

    //helper function Lift Coefficient = 2 * Flift / p v^2 SAwing (using lift from previous update loop for coefficient)
    private float getCoefficientOfLift(float vMag, float q)
    {
        //since Coefficient = 2 * Flift / p v^2 SAwing
        //q = p v^2 / 2
        //2 * Flift / p v^2 SAwing = 2 * Flift / 2 * q = Flift / q
        if (previousTotalLift == 0) 
        {
            // Estimate initial lift using dynamic pressure and wing area
            previousTotalLift = q * getEffectiveWingArea() * 0.4f; // 0.4 is a typical CL guess
        }
        return previousTotalLift / q;
    }

    //force of gravity is just Mass * AccelerationOfGrav
    private float ForceOfGravity()
    {
        return (rb.mass * ACCELERATION_OF_GRAVITY);//consider using other equation (that uses both masses and distance) to incorporate other planets
    }

    //gets coefficient of form drag
    private float getCoefficientOfFormDrag(float velocityMag){
        if (velocityMag <= 0f || previousTotalDrag <= 0f) {
            return 0f; // prevent division by zero
        }

        // Cd = (2 * FdragTotal) / (DENSITY_OF_AIR * V^2 * Sfront)
        return (2f * previousTotalDrag) / (DENSITY_OF_AIR * Mathf.Pow(velocityMag, 2) * getEffectiveFrontArea());
    }

    //gets coefficient of skin friction drag
    private float getCoefficientOfSkinFrictionDrag(float velocityMag)
    {
        float reynoldsNumber = getReynoldsNumber(velocityMag);
        if (reynoldsNumber <= 0f)
        {
            return 0f; //prevent divide-by-zero
        }
        //Cf =  1.328 / sqrt(Re)
        return BLASIUS_LAMINAR_DRAG_COEFFICIENT / Mathf.Sqrt(reynoldsNumber);
    }

    // wingspanTotal^2 / wingAreaTotal = Aspect Ratio
    private float getAspectRatio(float wingspan, float wingsArea)
    {
        return Mathf.Pow((wingspan), 2f) / (wingsArea);
    }

    // wingspanTotal^2 / wingAreaTotal = Aspect Ratio
    private float getAspectRatioFromHalf(float halftotalwingspan, float halftotalwingsArea)
    {
        //multiplied by two for each wing (currently assuming symmetry) and then the 4/2 simplifies to 2/1
        return (2 * Mathf.Pow((halftotalwingspan), 2f)) / (halftotalwingsArea);
    }

    //TODO: use lift induced drag factor way (more accurate)
    private float getOswaldApproximation(float AR)
    {
        //current oswald calculation (empirical approximation that is +-10 error for subsonic airfract)
        return (1.78f * (1.0f - .045f * Mathf.Pow(AR, .68f))) / Mathf.Pow(AR, .15f);
    }

    // //need to know lift coefficient for better accuracy than empirical approximation
    // private float getOswaldNumber(float liftCoefficient, float aspectRatio)
    // {
    //     //optimal oswald calculation (empirical approximation is less accurate for subsonic airfract)
    //     return 1 / (Mathf.PI * liftCoefficient * aspectRatio);
    // }

    //p * V * L / mu
    private float getReynoldsNumber(float velocityMag)
    {
        if (velocityMag < 0f)
        {
            return 0f; //prevent negative number
        }
        //TODO: verify and calculate L as mean aerodynamic chord (MAC)
        float MAC = physNums.getMAC();
        if (MAC <= 0f)
        {
            return 0f; //return 0 early
        }

        return velocityMag * DENSITY_OF_AIR * MAC / DYNAMIC_VISCOSITY_OF_AIR;
    }

    //fitness score is x distance travelled from start
    public float getFitnessScore()
    {
        return transform.position.x - startingFitness;//subtract current x from starting x to get travelled dist
    }

    //sets the surface areas, center of mass, etc used in flight calculations
    public void SetPhysicsResults(PaperAirplanePhysicsAttributes results)
    {
        physNums = results; //contains surface area and mass for aerodynamic equations
    }

    //sets the gene sequence field by cloning the passed in gene sequence
    public void SetGeneSequence(GeneSequence geneSequence)
    {
        geneSeq = geneSequence.Clone(); //create copy of gene sequence and save for future use
    }

    public void setGeneManager(GeneManager geneM)
    {
        geneManager = geneM;
    }
    //destroy object when meshCollider reaches the ground
    //use void OnCollisionEnter to determine ground collision
}