using Unity.VisualScripting;
using UnityEngine;
using static SemiCircleFoldingAlgorithm;

/**
 * script to be attatched to each glider to calculate aerodynamic pathing based on PaperAirplanePhysicsAttributes and current velocity/rotations
 * 
 * @author Grant Benson
 **/
public class GliderFlight : MonoBehaviour
{
    GeneSequence geneSeq; //gene sequence containing representations for glider creation
    PaperAirplanePhysicsAttributes physNums;
    Transform parentTransform; //glider object
    Rigidbody rb; //rigid body for glider to perform torque on
    //TODO: add a mesh collider and use the mesh generated by triangleMeshGenerator

    float startingFitness;
    float fitnessScore;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        float lifeSpan = 2.5f; //use random lifespan to test camera manager
        //Destroy(transform.parent.gameObject, lifeSpan); //destroy this object after lifespan
        // Get the parent of the current GameObject
        parentTransform = transform.parent;
        //set fitness score to x value on start
        startingFitness = parentTransform.position.x;
        //TODO: get rigid body of glider
        //rb = GetComponent<Rigidbody>();
    }

    // Update is called once per frame
    void Update()
    {
        //TODO: use gene sequence.GetInitialVelocity() to create linear flight paths for testing
        if (physNums.CanFly())
        {
            //add movement to parent position
            float xMovementAmount = geneSeq.GetInitialVelocity() * Time.deltaTime;
            float yMovementAmount = 2 * Time.deltaTime;
            parentTransform.position += new Vector3(xMovementAmount, -yMovementAmount, 0);
        }
    }

    //fitness score is x distance travelled from start
    public float getFitnessScore(){
        return parentTransform.position.x - startingFitness;//subtract current x from starting x to get travelled dist
    }

    //sets the surface areas, center of mass, etc used in flight calculations
    public void SetPhysicsResults(PaperAirplanePhysicsAttributes results)
    {
        physNums = results; //contains surface area and mass for aerodynamic equations
    }

    //sets the gene sequence field by cloning the passed in gene sequence
    public void SetGeneSequence(GeneSequence geneSequence)
    {
        geneSeq = geneSequence.Clone(); //create copy of gene sequence and save for future use
    }

    //before destroy each glider needs to save distance and gene sequence in gene manager
    void OnDestroy() //consider using OnDisable() in order to perform update a bit before memory cleanup
    {
        //update gene manager with the gene sequence and fitness score (distance travelled in x direction)
        geneManager.updateBestCompetitor(geneSeq, getFitnessScore());
    }

    //destroy object when meshCollider reaches the ground
    //use void OnCollisionEnter to determine ground collision
}
