using System;
using Unity.VisualScripting;
using UnityEngine;
using static SemiCircleFoldingAlgorithm;

/**
 * script to be attatched to each glider to calculate aerodynamic pathing based on PaperAirplanePhysicsAttributes and current velocity/rotations
 * 
 * @author Grant Benson
 **/
public class GliderFlight : MonoBehaviour
{
    GeneSequence geneSeq; //gene sequence containing representations for glider creation
    PaperAirplanePhysicsAttributes physNums;
    Rigidbody rb; //rigid body for glider to perform torque on
    //TODO: add a mesh collider and use the mesh generated by triangleMeshGenerator
    GeneManger geneManager;//ref to gene manager to save upon crash

    float startingFitness;
    float fitnessScore;
    private Action<GliderFlight, string, float> onDestroyCallback;

    //function passed in by game manager to update ui/camera on death
    public void SetOnDestroyCallback(Action<GliderFlight, string, float> callback)
    {
        onDestroyCallback = callback; //calls HandleGliderDestroyed function in game manager
    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        float maxLifeSpan = 8f; // Set lifespan before destruction
        Destroy(gameObject, UnityEngine.Random.Range(2, maxLifeSpan)); // Destroys this GameObject after max lifeSpan seconds
        // Get the parent of the current GameObject and set fitness score to x value on start
        startingFitness = transform.position.x;
        //TODO: get rigid body of glider
        //rb = GetComponent<Rigidbody>();
    }

    // Update is called once per frame
    void Update()
    {
        //TESTING: using gene sequence.GetInitialVelocity() to create linear flight paths
        if (physNums.CanFly())
        {
            //Debug.Log("glider fly :)");
            //add movement to parent position
            float xMovementAmount = geneSeq.GetInitialVelocity() * Time.deltaTime;
            float yMovementAmount = 2 * Time.deltaTime;
            transform.position += new Vector3(xMovementAmount, -yMovementAmount, 0);
        }
/*        else
        {
            Debug.Log("glider cannot fly :(");
        }*/

        //END OF TESTING: camera should follow lead glider
    }

    //fitness score is x distance travelled from start
    public float getFitnessScore(){
        return transform.position.x - startingFitness;//subtract current x from starting x to get travelled dist
    }

    //sets the surface areas, center of mass, etc used in flight calculations
    public void SetPhysicsResults(PaperAirplanePhysicsAttributes results)
    {
        physNums = results; //contains surface area and mass for aerodynamic equations
    }

    //sets the gene sequence field by cloning the passed in gene sequence
    public void SetGeneSequence(GeneSequence geneSequence)
    {
        geneSeq = geneSequence.Clone(); //create copy of gene sequence and save for future use
    }

    //before destroy each glider needs to save distance and gene sequence in gene manager
    void OnDestroy() //consider using OnDisable() in order to perform update a bit before memory cleanup
    {
        float finalFitnessScore = getFitnessScore();
        //update gene manager with the gene sequence and fitness score (distance travelled in x direction)
        geneManager.UpdateBestCompetitor(geneSeq, finalFitnessScore);
        onDestroyCallback(this, geneSeq.getName(), finalFitnessScore); // Pass the glider flight instance to the callback to be destroyed
        
    }

    public void setGeneManager(GeneManger geneM)
    {
        geneManager = geneM;
    }
    //destroy object when meshCollider reaches the ground
    //use void OnCollisionEnter to determine ground collision
}
